// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciregulqzdtflmdszkjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpcmVndWxxemR0ZmxtZHN6a2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzEyMzksImV4cCI6MjA3NDU0NzIzOX0.PVx707vkxVp1PPYPz1xpaimDL3RvPDbkUppWpbllEUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});